# Generated by Django 3.0.8 on 2020-07-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('escrv', models.IntegerField()),
                ('material', models.IntegerField()),
                ('grp_merc', models.IntegerField()),
                ('qtd_faturad', models.IntegerField()),
            ],
        ),
    ]
