# Generated by Django 3.0.8 on 2020-07-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='qtd_faturad',
            field=models.CharField(max_length=5),
        ),
    ]
