# Generated by Django 3.0.8 on 2020-07-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200724_0044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendas',
            table='vendas',
        ),
    ]
